# SPDX-FileCopyrightText: 2022 Leroy Hopson <copyright@leroy.geek.nz>
#
# SPDX-License-Identifier: CC0-1.0
name: "Update Quotes"

on:
  push:
  schedule:
    - cron: 0 8,23 * * *

jobs:
  check-reuse:
    name: "Check REUSE Compliance"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: fsfe/reuse-action@v1
  scrape:
    name: "Update Quotes"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: pip install -r requirements.txt
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: sqlite3
          debug: 'false'
      - name: Scrape quotes
        run: |
          $(npm bin)/cypress run
          ./scrape.sh
        env:
          CYPRESS_KERNEL_USERNAME: ${{ secrets.CYPRESS_KERNEL_USERNAME }}
          CYPRESS_KERNEL_PASSWORD: ${{ secrets.CYPRESS_KERNEL_PASSWORD }}
      - name: Update quotes
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: quotes
